server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-payment-service          #匹配后提供服务的路由地址，如果要实现负载均衡则使用服务名称
          filters:
            - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的url加上请求头，名为X-Request，值为1024
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由
            - After=2020-03-08T10:59:34.102+08:00[Asia/Shanghai]    #断言，只能在该时间之后访问

        - id: payment_routh2
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/feign/timeout   #断言,路径相匹配的进行路由


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka


